name: MirrorSentinel Daily Run

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4
      - name: Run MirrorSentinel Enhanced Runner
        run: python mirror_sentinel/full_runner_enhanced.py

  - name: Run Template Mutation
    run: python mirror_sentinel/mutate_and_update_templates.py
